// <auto-generated />
using System;
using Kook.Bot.Crowdin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kook.Bot.Crowdin.Migrations
{
    [DbContext(typeof(CrowdinBotDbContext))]
    [Migration("20220826081226_AddTermItems")]
    partial class AddTermItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Kook.Bot.Crowdin.Data.Models.TermEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("GlossaryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lemma")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartOfSpeech")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentEntityId");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("Kook.Bot.Crowdin.Data.Models.TermEntity", b =>
                {
                    b.HasOne("Kook.Bot.Crowdin.Data.Models.TermEntity", "ParentEntity")
                        .WithMany("Translations")
                        .HasForeignKey("ParentEntityId");

                    b.Navigation("ParentEntity");
                });

            modelBuilder.Entity("Kook.Bot.Crowdin.Data.Models.TermEntity", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
